### ISSUE TITLE
rakuten tv

### ISSUE THREAD

**Issue by yakumo43** [tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER#1]
rakuten tv downloader please

podria ser rakuten tv por favor? gracias por leer

https://rakuten.tv/es

p.d: yo soy español tambien

**Comment by tuprimafromtomelloso** [comment]
Buenas, lo siento pero no voy a actualizar el código para más sitios. Además no tengo cuenta en Rakuten. Siempre puedes adaptarlo a más webs tu mismo, es sencillo.
