### ISSUE TITLE
tengo una version que mejore

### ISSUE THREAD

**Issue by Batacax** [tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER#3]
tengo una version que detecta los archivos .json y descarga todo automaticamente

**Comment by tuprimafromtomelloso** [comment]
genial! la compartes?

**Comment by pitoloco** [comment]
y las claves como las consigo por que ha dejado de funcionar guesser no?

**Comment by tuprimafromtomelloso** [comment]
puedes usar este script.

https://github.com/WKS-uwu/WKS-KEY

**Comment by pitoloco** [comment]
> puedes usar este script.
> 
> https://github.com/WKS-uwu/WKS-KEY

ok gracias lo pruebo a ver

**Comment by pitoloco** [comment]
Nada no me sale con movistar, reproduzco la resistencia filtro por drm license y mpd, copio en curl bash lo paso a python, copio todo y ejecuto l3.py y nada, hago algo mal?
He probado con mpd license y drm

**Comment by Batacax** [comment]
dejame ver ahora lo reviso

**Comment by tuprimafromtomelloso** [comment]
> Nada no me sale con movistar, reproduzco la resistencia filtro por drm license y mpd, copio en curl bash lo paso a python, copio todo y ejecuto l3.py y nada, hago algo mal? He probado con mpd license y drm
> 
> por cierto acabar de chapar la web del script

Tienes que pegar la licencia pasada a Python dentro de headers.py

Luego ejecutas Python l3.py

Metes el pssh que está en el mpd (en F12 abres el .mpd en una pestaña nueva y el primer pssh que te sale es el que corresponde a widevine)

Copias ese pssh en el script en ejecución y luego te pedirá la URL de la licencia (sin convertir a Python). En F12 licenses botón derecho copiar dirección.

Metes la URL al script pulsas intro y te dará la key, la guardas, ejecutas mi bash, sigues los pasos y listo.

**Comment by Batacax** [comment]
> > Nada no me sale con movistar, reproduzco la resistencia filtro por drm license y mpd, copio en curl bash lo paso a python, copio todo y ejecuto l3.py y nada, hago algo mal? He probado con licencia mpd y drm
> > por cierto acabar de chapar la web del script
> 
> Tienes que pegar la licencia pasada a Python dentro de headers.py
> 
> Luego ejecutas Python l3.py
> 
> Metes el pssh que está en el mpd (en F12 abres el .mpd en una pestaña nueva y el primer pssh que te sale es el que corresponde a widevine)
> 
> Copias ese pssh en el script en ejecución y luego te pedirá la URL de la licencia (sin convertir a Python). En F12 licencias con respuesta POST botón derecho copiar dirección.
> 
> Metes la URL al script pulsas intro y te dará la key, las guardas, ejecutas mi bash, que en el caso de La Resistencia es Un Audio sin Subtítulos, sigues los pasos y listo.
> 
> Filmin es más sencillo está todo dentro del mpd aunque hay algunas que no y que generarlos en la web de Axiom Tools.

esta re complicado eso no es mas facil remplazar los archivos de widevine y obtener las key rapidamente

**Comment by pitoloco** [comment]
> > Nada no me sale con movistar, reproduzco la resistencia filtro por drm license y mpd, copio en curl bash lo paso a python, copio todo y ejecuto l3.py y nada, hago algo mal? He probado con mpd license y drm
> > por cierto acabar de chapar la web del script
> 
> Tienes que pegar la licencia pasada a Python dentro de headers.py
> 
> Luego ejecutas Python l3.py
> 
> Metes el pssh que está en el mpd (en F12 abres el .mpd en una pestaña nueva y el primer pssh que te sale es el que corresponde a widevine)
> 
> Copias ese pssh en el script en ejecución y luego te pedirá la URL de la licencia (sin convertir a Python). En F12 licenses con respuesta POST botón derecho copiar dirección.
> 
> Metes la URL al script pulsas intro y te dará la key, la guardas, ejecutas mi bash, que en el caso de La Resistencia es Un Audio sin Subtítulos, sigues los pasos y listo.
> 
> Filmin es más sencillo está todo dentro del mpd aunque hay algunas que no y hay que generarlos en la web de Axiom Tools.

gracias por la explicacion sigue sin salirme, una pregunta tonta lo hago desde cmd todo, al ser curl bash tengo que hacerlo desde bash?

**Comment by tuprimafromtomelloso** [comment]
Se hace con el CMD si. Mañana puedo colocar unas imágenes de cómo hacerlo. No tardas ni dos minutos.

**Comment by pitoloco** [comment]
> Se hace con el CMD si. Mañana puedo colocar unas imágenes de cómo hacerlo. No tardas ni dos minutos.

ok muchisimas gracias

**Comment by pitoloco** [comment]
por si te sirve de algo he sacado el pssh de atresplayer, he filtrado por mani de manifest me ha salido le he dado a abrir ventana nueva y lo descargo y ahi viene, la licencia no sale

**Comment by tuprimafromtomelloso** [comment]
https://user-images.githubusercontent.com/88166727/144993473-d55e3fbb-f272-4dbb-bd11-ad18dfaa9548.mp4

**Comment by pitoloco** [comment]
> Wvm+-1.mp4

Muchísimas gracias al final lo conseguí anoche me faltaban módulos para hacer correr l3.py conseguí tb Atresplayer, el mpd cogí el segundo pssh que sale y para a licencia hay que filtrar por proxy y me dio la clave

**Comment by tuprimafromtomelloso** [comment]
cada sitio tiene su historia, aunque si sabes por donde buscar al final la consigues y una vez sepas como hacerlo ya es muy fácil.

El script básico solo trabaja M+ y FLMN por la nomenclatura de sus archivos, puedes adaptarlo a todos los sitios que quieras editando el .bat ya que hace uso de ytb-dlp y este es muy versátil.

Cierro el post, si alguna vez necesitas el video ya sabes donde está. Un saludo.

**Comment by pitoloco** [comment]
Venga otro para ti y mil gracias de nuevo
