### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by xiaoxiaoliya** [tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER#4]
Ahora la clave wks no es válida, parece que hay una restricción en el encabezado y no se puede solicitar

**Comment by tuprimafromtomelloso** [comment]
Hi, just tested wks-keys and its working good!

**Comment by xiaoxiaoliya** [comment]
> 嗨，刚刚测试了 wks-keys 并且它运行良好！

Eres tan dedicado, gracias. No sé por qué no funciona en mi computadora y no puedo llegar al paso de ingresar pssh, pero todavía funciona hace unos días. ¿Agregaron alguna información al encabezado?

**Comment by xiaoxiaoliya** [comment]
> 嗨，刚刚测试了 wks-keys 并且它运行良好！



> 嗨，刚刚测试了 wks-keys 并且它运行良好！

Quizás puedas probar otros sitios web encriptados de Google

**Comment by xiaoxiaoliya** [comment]
https://www.kktv.me/
Necesita una VPN taiwanesa, lo que le causa problemas. De lo contrario, no es necesario que realice este trabajo.

**Comment by tuprimafromtomelloso** [comment]
i do not have a vpn for that country. Anyways, some sites needs a extra info in the headers because of sending the license in a json. I cant do anything about that, for our luck, in spain, providers do not use that method.

**Comment by tuprimafromtomelloso** [comment]
maybe this video can help you to resolve your problem.

https://github.com/tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER/issues/3#issuecomment-987683313

im closing the thread.

**Comment by xiaoxiaoliya** [comment]
> 嗨，刚刚测试了 wks-keys 并且它运行良好！



> 我没有那个国家的 VPN。无论如何，由于在 json 中发送许可证，某些站点需要在标题中提供额外信息。我对此无能为力，为了我们的运气，在西班牙，供应商不使用这种方法。



> 我没有那个国家的 VPN。三次供应，因为在 json 中发送，部分站点需要在标题中提供额外的使用信息。

Gracias, ¿puede enviarme una copia de sus trabajos? Me pregunto si hay algún problema con mi copia. xiao1050499657@gmail.com

> maybe this video can help you to resolve your problem.
> 
> [#3 (comment)](https://github.com/tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER/issues/3#issuecomment-987683313)
> 
> im closing the thread.



> i do not have a vpn for that country. Anyways, some sites needs a extra info in the headers because of sending the license in a json. I cant do anything about that, for our luck, in spain, providers do not use that method.
Gracias, ¿puede enviarme una copia de sus trabajos? Me pregunto si hay algún problema con mi copia. xiao1050499657@gmail.com

> 也许这个视频可以帮助你解决你的问题。
> 
> [#3（评论）](https://github.com/tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER/issues/3#issuecomment-987683313)
> 
> 我正在关闭线程。
Gracias, ¿puede enviarme una copia de sus trabajos? Me pregunto si hay algún problema con mi copia. xiao1050499657@gmail.com

**Comment by xiaoxiaoliya** [comment]
> 也许这个视频可以帮助你解决你的问题。
> 
> [#3（评论）](https://github.com/tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER/issues/3#issuecomment-987683313)
> 
> 我正在关闭线程。
Gracias, ¿puede enviarme una copia de sus trabajos? Me pregunto si hay algún problema con mi copia。xiao1050499657@gmail.com
