### ISSUE TITLE
estoy de regreso otra vez

### ISSUE THREAD

**Issue by xiaoxiaoliya** [tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER#5]
Disculpe de nuevo, ¿qué debo hacer si no se encuentra la licencia en la red?

**Comment by tuprimafromtomelloso** [comment]
Hi, the license must appear in Dev Tools. Filter for wv, widevine, cert, token, license etc

**Comment by xiaoxiaoliya** [comment]
> Hi, the license must appear in Dev Tools. Filter for wv, widevine, cert, token, license etc
Eres un genio, pero ahora tengo un nuevo problema.
![image](https://user-images.githubusercontent.com/94291982/145368732-f8585d7d-bb7f-47ba-9fc4-c50bdbb21db6.png)

**Comment by xiaoxiaoliya** [comment]
> Hi, the license must appear in Dev Tools. Filter for wv, widevine, cert, token, license etc



> Hi, the license must appear in Dev Tools. Filter for wv, widevine, cert, token, license etc

Lo logré, muy feliz, ¡gracias!

**Comment by Batacax** [comment]
buenas podrian pasarme el wks-keys ya trate de 
buscarlo pero no lo encuentro
