### ISSUE TITLE
como sigue,Amigo, estoy aquí de nuevo!

### ISSUE THREAD

**Issue by xiaoxiaoliya** [tuprimafromtomelloso/M-FLMN-BATCH-DOWNLOADER#6]
¿Cómo puedo cambiar su secuencia de comandos para usarla en otros sitios web? O, ¿qué conocimiento debo aprender?

**Comment by tuprimafromtomelloso** [comment]
Hola! normalmente con cambiar el nombre que genera la descarga del .mpd suele funcionar. En concreto esto.

ren "E:\Descargas\movistar+\%folder%\*.mp4" encrypted.mp4

ren "E:\Descargas\movistar+\%folder%\*.m4a" encrypted.m4a

ren "E:\Descargas\movistar+\%folder%\*.m4a" encrypted2.m4a
